### ISSUE TITLE
exome mode running error

### ISSUE THREAD

**Issue by yuxinPenny** [DepledgeLab/DRUMMER#11]
Running with the test data in exome mode leads to the following error:

[('/data/yuxin/2021Fall/HomoSapiens/HMEC/HMEC_WT/bam/HMEC_WT_g.bam', '/data/yuxin/2021Fall/HomoSapiens/HMEC/HMEC_ALKBH5/bam/HMEC_ALKBH5_g.bam')]
Current_file /data/yuxin/2021Fall/HomoSapiens/HMEC/HMEC_WT/drummer_result/transcript/chr1.fa
/data/yuxin/2021Fall/HomoSapiens/HMEC/HMEC_WT/drummer_result/HMEC_WT_g-HMEC_ALKBH5_g/map/chr1.unmod.genomecov.txt
Traceback (most recent call last):
  File "/home/yuxin/DRUMMER/DRUMMER.py", line 54, in <module>
    test_exome.main(transcriptome_file,treatment_bam,name,control_bam,odds,padj,m6A,fraction_diff,output_dir,'exome',deletion)
  File "/home/yuxin/DRUMMER/modules/test_exome.py", line 192, in main
    summary_df = run_summary(output_dir+'/'+repl + '/complete_analysis/',m6A_status)
  File "/home/yuxin/DRUMMER/modules/summary.py", line 41, in run_summary
    final_candidates = all_candidates[keep_columns]
  File "/home/yuxin/miniconda3/envs/DRUMMER/lib/python3.8/site-packages/pandas/core/frame.py", line 2908, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "/home/yuxin/miniconda3/envs/DRUMMER/lib/python3.8/site-packages/pandas/core/indexing.py", line 1254, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "/home/yuxin/miniconda3/envs/DRUMMER/lib/python3.8/site-packages/pandas/core/indexing.py", line 1298, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['chr_ctrl', 'ref_ctrl', 'pos_ctrl', 'depth_ctrl', 'depth_treat',\n       'ref_fraction_ctrl', 'ref_fraction_treat', 'frac_diff', 'odds_ratio',\n       'log2_(OR)', 'p_values_OR_adj', 'eleven_bp_motif', 'G_test', 'padj',\n       'accumulation', 'depletion', 'nearest_ac', 'nearest_ac_motif',\n       'homopolymer', 'is_SNP'],\n      dtype='object')] are in the [columns]"

I also came up with above error with my own data.

**Comment by DepledgeLab** [comment]
Could you provide the full input command so we can look into this?

Please also be aware that we do not recommend running exome mode for large
eukaryotes due to processing time. Moreover, where high quality
transcriptome exist (e.g. for H sapiens) then isoform mode is much superior
(speed + data quality).

**Comment by JonAbebe** [comment]
Could you try moving to the actual DRUMMER directory and re-running the command, i.e.:

cd /home/yuxin/DRUMMER/

python DRUMMER.py
-r /data/yuxin/2021Fall/Reference/hg38.fa
-n chr1
-c /data/yuxin/2021Fall/HomoSapiens/HMEC/HMEC_WT/bam/HMEC_WT_g.bam
-t /data/yuxin/2021Fall/HomoSapiens/HMEC/HMEC_ALKBH5/bam/HMEC_ALKBH5_g.bam
-o /data/yuxin/2021Fall/HomoSapiens/HMEC/HMEC_WT/drummer_result
-a exome
-m True
